### ISSUE TITLE
FUSE caching passes in outdated params to plugin script

### ISSUE THREAD

**Issue by ekinanp** [puppetlabs/wash#356]
It's common for external plugin authors to adjust their scripts while a Wash daemon is running. Unfortunately when they go ahead and try to run any shell command that interacts with the FUSE layer (e.g. like `ls` and `cat`), those changes don't show up. This is because FUSE caches nodes for a long time, so external plugin script invocations will use the old node's script arguments instead of the new nodes. This means that when one updates a node's state, for example, Wash will pass-in the old state instead of the new state when invoking the external plugin script.

**Comment by ekinanp** [comment]
I think this was fixed in https://github.com/puppetlabs/wash/issues/345 -- we'll just need to push out a new release.

**Comment by MikaelSmith** [comment]
Ok. I'm happy to hit release on that.

**Comment by MikaelSmith** [comment]
@binford2k can you check whether this still happens with Wash 0.5.0?

**Comment by binford2k** [comment]
It does not appear to still happen. I altered the `state` parameter returned by the `list` method, and then catted the same file and observed the difference in the command invoked. I think this can be closed.

**Comment by MikaelSmith** [comment]
Thanks!
